### ISSUE TITLE
Add nightly operator installation

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/webfuse#13]
The installation procedure for nightly operators seems to be different from stable channels. We need to add automation for that.

**Comment by mukrishn** [comment]
Followed this procedure -[ Custom catalog source](https://docs.engineering.redhat.com/display/MULTIARCH/How+To+Test+Red+Hat+ART+Operators)

But instead of using the staged Index Images - `brew.registry.redhat.io/rh-osbs/iib-pub-pending:v4.7` I'm letting the user to pick the suitable/available custom version for each operator because the staged image may not have the exact operator version we need. 

For ex - as of 11/30, staged image has not included SRIOV 4.7 operator so have to use - `brew.registry.redhat.io/rh-osbs/iib:25944` for SRIOV. This is QE's approach [here](https://gitlab.cee.redhat.com/cf/docs/pipeline/-/blob/master/doc/Operators/Test.md#apply-the-custom-catalogsource)

Users need to provide IIB IDs for each operator. 
```
iib_id:
  sriov: 25944     #openshift-sriov-network-operator
  osv: 26761     #openshift-virtualization 
  clo: 26761     #cluster-logging-operator
  amq: 26761     #amq-operator
  pao: 26761     #performance-addon-operator
  eso: 26761     #elastic-search-operator
```
To get the right IIB IDs, find the operator version from this [link](http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/)(takes longer to load) and navigate to `index_image.txt` file to get the ID. 
@smalleni any thoughts about this approach?
